api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/json']
        mime_types: ['multipart/form-data']
    collection:
        pagination:
            items_per_page: 10
    formats:
        jsonld: ['application/ld+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
